### ISSUE TITLE
citation info for lessons in The Carpentries Incubator

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/organization#4]
Below are my suggested guidelines for providing citation info in the `CITATION` file of Incubator lesson repositories. I guess this should end up in the Curriculum Development Handbook. But I'm posting here for now as I'm not sure where would be the appropriate place within the CDH and anyway haven't yet had time to familiarise myself with Bookdown...

I have two main concerns:
1. I'm personally a big supporter of the Citation File Format project and what they're trying to achieve. But I'm not sure `.cff` format is ideal for lesson material (it's designed more for making software citable).
2. I still find the concept/version DOI thing confusing: really I think it would be better to use the DOI of the specific version but (as far as I can tell) it still isn't possible to reserve a DOI for a GitHub release, so you'd end up with the old DOI in the CITATION file of the released version... For a lesson, it's probably not such a big deal to use the concept DOI, and I see that's what's happening with official Carpentries releases on Zenodo.

All comments and suggestions, on the above points or anything else, are welcome. 

---

## Option 1: Basic text file

Recommended structure

```
author(s)
lesson title[, version number if releasing via Zenodo-GitHub integration]
lesson pages URL
[concept DOI if releasing via Zenodo-GitHub integration]
```

minimal example:

```
Toby Hodges
Building Websites with Jekyll and GitHub/GitLab
https://carpentries-incubator.github.io/building-websites-with-jekyll-and-github-or-gitlab
```

Example with release published to Zenodo

```
Toby Hodges, Aleksandra Nenadic, Julian Karl Bauer, Anne Foullioux, Sarah Stevens, Renato Alves
Building Websites with Jekyll and GitHub/GitLab, v0.1
https://carpentries-incubator.github.io/building-websites-with-jekyll-and-github-or-gitlab
10.5281/zenodo.4013386
```

(note that with future releases, the version number would need to change in the example CITATION file above but the DOI should remain unchanged)

## Option 2: Using [Citation File Format](https://citation-file-format.github.io/)

Recommended structure

```
cff-version: 1.1.0 
authors:
  - family-names: author family name(s)
    given-names: author first/given name(s)
    [orcid: author ORCID]
title: lesson title
[version: version number if releasing via Zenodo-GitHub integration]
date-released: yyyy-mm-dd
repository: GitHub repository URL
url: lesson pages URL
[doi: concept DOI if syncing releases with Zenodo]
```
(Note that [other information about authors, including affiliation and name suffix/particle, can be provided](https://github.com/citation-file-format/citation-file-format#notable-reference-keys))

minimal example:

```
cff-version: 1.1.0 
authors:
  - family-names: Hodges
    given-names: Toby
    orcid: https://orcid.org/0000-0003-1766-456X
title: Building Websites with Jekyll and GitHub/GitLab
date-released: 2020-09-03
repository: https://github.com/carpentries-incubator/building-websites-with-jekyll-and-github-or-gitlab
url: https://carpentries-incubator.github.io/building-websites-with-jekyll-and-github-or-gitlab
```

Example with release published to Zenodo

```
cff-version: 1.1.0 
authors:
  - family-names: Hodges
    given-names: Toby
    orcid: https://orcid.org/0000-0003-1766-456X
  - family-names: Nenadic
    given-names: Aleksandra
  - family-names: Bauer
    given-names: Julian Karl
  - family-names: Foullioux
    given-names: Anne
  - family-names: Stevens
    given-names: Sarah
  - family-names: Alves
    given-names: Renato
title: Building Websites with Jekyll and GitHub/GitLab
version: 0.1
date-released: 2020-09-03
repository: https://github.com/carpentries-incubator/building-websites-with-jekyll-and-github-or-gitlab
url: https://carpentries-incubator.github.io/building-websites-with-jekyll-and-github-or-gitlab
doi: 10.5281/zenodo.4013386
```

(note that with future releases, the version number would need to change in the example CITATION file above but the DOI should remain unchanged)

## Publishing releases via Zenodo

To include DOI in CITATION file:
1. (if syncing with Zenodo for the first time) log into Zenodo via GitHub; activate Zenodo integration for your GitHub account; make sure Zenodo integration has access to organizational (e.g. carpentries-incubator) repo (GitHub -> Settings -> Applications -> OAuth Applications -> Zenodo -> Organization access)
2. log into **Zenodo**
3. click dropdown arrow next to your account name (top right), then click "GitHub"
4. find your lesson repository and (if you're making the first release for this repository) activate Zenodo tracking by clicking the button next to the repository name
5. go to your lesson repository **on GitHub**
6. click "Create a new release" link under "Releases" (right)
7. give a tag, name, and (optionally) a description of the release
8. go **back to Zenodo** and click "Upload" (top menu)
9. click on your new release in the Zenodo upload listing
10. click "Edit" change "Upload type" to "Lesson"
11. fill in/adjust the relevant details, providing a short description of the lesson
     - under authors, remove all authors who haven't contributed to the lesson content (many more people will be listed, who contributed to The Carpentries lesson template)
12. click "Save" and "Publish"
13. navigate back to the "GitHub" page on Zenodo (see step 2)
14. click on the _badge_ below the name of the relevant repository (which should be at or near the top of the listing)
15. copy the Markdown snippet at in the pop-up and add this to your repostory's README.md **on GitHub**
     - clicking this badge button will always take users directly to the Zenodo listing of the _latest release_ of your lesson
16. add the DOI displayed on the badge to your CITATION file

### Making a new release

When making new releases of the same lesson in future (e.g. to update author list or to reflect significant updates to the material), follow steps 2-12 above and update the version number (and any other outdated information) in your CITATION file.
